# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"\x0b\n\tUserEmpty\"\x1c\n\x0cUserResponse\x12\x0c\n\x04name\x18\x01 \x01(\t23\n\x0bUserService\x12$\n\x07GetUser\x12\n.UserEmpty\x1a\r.UserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USEREMPTY']._serialized_start=14
  _globals['_USEREMPTY']._serialized_end=25
  _globals['_USERRESPONSE']._serialized_start=27
  _globals['_USERRESPONSE']._serialized_end=55
  _globals['_USERSERVICE']._serialized_start=57
  _globals['_USERSERVICE']._serialized_end=108
# @@protoc_insertion_point(module_scope)
